### ISSUE TITLE
AgileObjects dependencies and .NET Standard 2.0 target

### ISSUE THREAD

**Issue by bdovaz** [SIDOVSKY/EBind#1]
I have done 2 PR on the 2 dependencies of AgileObjects.ReadableExpressions which in turn depends on AgileObjects.NetStandardPolyfills because they do not target .NET Standard 2.0 which is a requirement for it to work in the Unity 3D game engine.

https://github.com/agileobjects/ReadableExpressions/pull/82
https://github.com/agileobjects/NetStandardPolyfills/pull/6

If they get to merge and release a new version on Nuget could you lift the version of these dependencies?

Thanks!

**Comment by SIDOVSKY** [comment]
> If they get to merge and release a new version on Nuget could you lift the version of these dependencies?

Sure! As soon as a new version is released.

Does it stop you from using EBind in Unity?
According to the .NET Standard [compatibility list](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support:~:text=Unity,TBD) all versions are supported for Unity.
.NET standard is [backward compatible](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-standard-versioning-rules:~:text=Additive%3A%20.NET%20Standard%20versions%20are%20logically,are%20no%20breaking%20changes%20between%20versions.), isnt it?

**Comment by bdovaz** [comment]
But the problem is that Unity includes .NET Standard 2.0 assemblies that conflict with assemblies you bring from Nuget when a package targets .NET Standard 1.x.

https://docs.unity3d.com/Manual/dotnetProfileSupport.html

As you know, one of the advantages of 2.0 over 1.x is the ability to minimize nuget dependencies.

Unity is not compatible with Nuget and having to add the assemblies and their dependencies by hand, you suffer many problems.

**Comment by SIDOVSKY** [comment]
If .NET Standard 2 is already embedded and you add nuget assemblies by hand, isn't it possible to skip .NET Standard 1.x assemblies and add just those:
```cs
EBind.dll
System.Runtime.CompilerServices.Unsafe.dll
AgileObjects.NetStandardPolyfills.dll
AgileObjects.ReadableExpressions.dll
```

**Comment by bdovaz** [comment]
Yes (I think it would work) but in my case I use this package to resolve nuget packages inside Unity and it's not possible:

https://github.com/xoofx/UnityNuGet

I use this package because some nuget packages have a really large dependency chain and it's really painful to download all of them manually.

**Comment by SteveWilkes** [comment]
Hi,

I've now uploaded a ReadableExpressions v2.6 preview release [to NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions) with a .NET Standard 2.0 target added - will hopefully release the non-preview version tomorrow or the day after.

All the best,

Steve

**Comment by bdovaz** [comment]
@SteveWilkes how is this going? I still see that you have no published a stable version of 2.6 release.

**Comment by SteveWilkes** [comment]
@bdovaz - sorry about that, I've been waiting on confirmation that an issue is fixed in the preview version.

If I've heard nothing in a couple of days I'll push the full versions.

**Comment by SteveWilkes** [comment]
Hi,

Just to let you know v2.6 of ReadableExpressions is now available [on NuGet](https://www.nuget.org/packages/AgileObjects.ReadableExpressions), and has a .NET Standard 2,0 target.

All the best,

Steve

**Comment by SIDOVSKY** [comment]
Yeah! Thank you, Steve!
I've also updated the dependencies.

@bdovaz, version [1.0.2](https://www.nuget.org/packages/EBind.NET/1.0.2) is published and ready for installation.
Please, leave some feedback about the problem and then we will close the issue.

**Comment by bdovaz** [comment]
It works in the Unity editor, I have to test on different platforms on AOT with IL2CPP.

Anyway I close the issue and if I find any concrete problem I will reopen another one.

Thanks for everything to both of you.
