### ISSUE TITLE
Doesn't work with Windows Form

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [SIDOVSKY/EBind#2]
It seems that EBind can only bind from my data to Winform Control but cannot bind from Control back to my data.
```csharp
public partial class MainForm : Form
{
    // auto implement using Fody
    public class Test : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public string Hello { get; set; }
    }

    EBinding binding;
    Test abc = new Test();
    public MainForm()
    {
        InitializeComponent();
        binding = new EBinding {
            BindFlag.TwoWay,
            () => txtHello.Text == abc.Hello,
        };
        abc.Hello = "ABC";
        // txtHello.Text is changed to "ABC"
        txtHello.Text = "DEF";
        // abc.Hello is still "ABC"
    }
}
```

**Comment by SIDOVSKY** [comment]
WinForms controls are platform-specific binding targets which have not been configured out of the box yet.
You need to initialize your app with the configuration code for the control properties that are actually used as a binding source in your project.

In case of a [TextBox.Text](https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.forms.textbox.text) property the configuration would be:
```cs
EBinding.DefaultConfiguration.ConfigureTrigger<TextBoxBase, string>(
    v => v.Text,
    (v, h) => v.TextChanged += h,
    (v, h) => v.TextChanged -= h);
```
See the [configuration docs](https://github.com/SIDOVSKY/EBind#member-triggers) for more info.
You might also find a [Xamarin.Android config](https://github.com/SIDOVSKY/EBind/blob/main/EBind/Platform/Configuration.android.cs) useful as a sample.

**Comment by Meigyoku-Thmn** [comment]
Thank you! Now I understand this.
