### ISSUE TITLE
Benchmark - comparison with Xamarin.Forms binding engine

### ISSUE THREAD

**Issue by raV720** [SIDOVSKY/EBind#3]
It would be great to see Xamarin.Forms binding engine in performance comparison

**Comment by SIDOVSKY** [comment]
Sure! Added benchmarks for the binding part of Xamarin.Forms view initialization (`InitializeComponent`).
Updated the readme with results.
Looks like Xamarin.Forms [typed bindings](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings) are a bit faster in construction but much slower in triggering.
